# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='book.proto',
  package='book',
  syntax='proto3',
  serialized_options=b'\n\007io.bookB\tBookProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\nbook.proto\x12\x04\x62ook\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2d\n\tBookShelf\x12*\n\x07\x61\x64\x64\x42ook\x12\r.book.Request\x1a\x0e.book.Response\"\x00\x12+\n\x08getBooks\x12\r.book.Request\x1a\x0e.book.Response\"\x00\x42\x1c\n\x07io.bookB\tBookProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='book.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='book.Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=43,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='book.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='book.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:book.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_BOOKSHELF = _descriptor.ServiceDescriptor(
  name='BookShelf',
  full_name='book.BookShelf',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=74,
  serialized_end=174,
  methods=[
  _descriptor.MethodDescriptor(
    name='addBook',
    full_name='book.BookShelf.addBook',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getBooks',
    full_name='book.BookShelf.getBooks',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKSHELF)

DESCRIPTOR.services_by_name['BookShelf'] = _BOOKSHELF

# @@protoc_insertion_point(module_scope)
